service: remak-thumbnailgen
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  timeout: 30
  memorySize: 1024
  environment:
    NODE_ENV: 'production'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource:
        - arn:aws:s3:::remak-documents/*
        - arn:aws:s3:::remak-thumbnails/*
  logRetentionInDays: 14
  layers:
    - arn:aws:lambda:ap-northeast-2:175033217214:layer:graphicsmagick:2
    - arn:aws:lambda:ap-northeast-2:764866452798:layer:ghostscript:15

functions:
  remak-thumbnail-gen:
    handler: src/handler.handler
    events:
      - s3:
          bucket: remak-documents
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true
      - s3:
          bucket: remak-documents
          event: s3:ObjectRemoved:*
          existing: true
          forceDeploy: true

plugins:
  - serverless-plugin-typescript
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 10
